### ISSUE TITLE
bug: Uncaught node.js Error

### ISSUE THREAD

**Issue by lebkayn** [rockiger/akiee#30]
when i try to change the order of tasks i get this error

Uncaught node.js Error 

TypeError: Cannot read property 'rank' of undefined
    at moveRank (/tmp/.org.chromium.Chromium.5iXFDe/js/updateRank.js:70:41)
    at Object.downRank (/tmp/.org.chromium.Chromium.5iXFDe/js/updateRank.js:33:5)
    at Object.onClickDownRank (file:///tmp/.org.chromium.Chromium.5iXFDe/js/app.js:391:20)
    at HTMLTableCellElement.onclick (file:///tmp/.org.chromium.Chromium.5iXFDe/index.html:1:89)

**Comment by rockiger** [comment]
Can you remember which task you reordered? To help me reproduce to problem.

**Comment by lebkayn** [comment]
it happened on todo-tasks, it works fine on doing & done.

**Comment by rockiger** [comment]
Can't reproduce.

**Comment by rockiger** [comment]
Can't reproduce.
